export const theme = [
    { value: '', label: 'default' },
    { value: 'black-tie', label: 'black-tie' },
    { value: 'blitzer', label: 'blitzer' },
    { value: 'cupertino', label: 'cupertino' },
    { value: 'custom-dark', label: 'custom-dark' },
    { value: 'custom-light', label: 'custom-light' },
    { value: 'dark-hive', label: 'dark-hive' },
    { value: 'dot-luv', label: 'dot-luv' },
    { value: 'eggplant', label: 'eggplant' },
    { value: 'excite-bike', label: 'excite-bike' },
    { value: 'flick', label: 'flick' },
    { value: 'hot-sneaks', label: 'hot-sneaks' },
    { value: 'humanity', label: 'humanity' },
    { value: 'overcast', label: 'overcast' },
    { value: 'redmond', label: 'redmond' },
    { value: 'smoothness', label: 'smoothness' },
    { value: 'start', label: 'start' },
    { value: 'sunny', label: 'sunny' },
    { value: 'ui-darkness', label: 'ui-darkness' },
    { value: 'ui-lightness', label: 'ui-lightness' },
    { value: 'vader', label: 'vader' },
] as const;

export const background = [
    { value: '', label: 'not-specified' },
    { value: 'fm-dark-background', label: 'Fm dark background' },
    { value: 'fm-light-background', label: 'Fm light background' },
    { value: 'no_background', label: 'No background' },
    { value: 'hq-background-blue-marine-lines', label: 'Blue marine lines' },
    { value: 'hq-background-blue-marine', label: 'Blue marine' },
    { value: 'hq-background-radial-blue', label: 'Radial blue' },
    { value: 'hq-background-gradient-box', label: 'Gradient box' },
    { value: 'hq-background-h-gradient-black-0', label: 'H gradient black 0' },
    { value: 'hq-background-h-gradient-black-1', label: 'H gradient black 1' },
    { value: 'hq-background-h-gradient-black-2', label: 'H gradient black 2' },
    { value: 'hq-background-h-gradient-black-3', label: 'H gradient black 3' },
    { value: 'hq-background-h-gradient-black-4', label: 'H gradient black 4' },
    { value: 'hq-background-h-gradient-black-5', label: 'H gradient black 5' },
    { value: 'hq-background-h-gradient-orange-0', label: 'H gradient orange 0' },
    { value: 'hq-background-h-gradient-orange-1', label: 'H gradient orange 1' },
    { value: 'hq-background-h-gradient-orange-2', label: 'H gradient orange 2' },
    { value: 'hq-background-h-gradient-orange-3', label: 'H gradient orange 3' },
    { value: 'hq-background-h-gradient-blue-0', label: 'H gradient blue 0' },
    { value: 'hq-background-h-gradient-blue-1', label: 'H gradient blue 1' },
    { value: 'hq-background-h-gradient-blue-2', label: 'H gradient blue 2' },
    { value: 'hq-background-h-gradient-blue-3', label: 'H gradient blue 3' },
    { value: 'hq-background-h-gradient-blue-4', label: 'H gradient blue 4' },
    { value: 'hq-background-h-gradient-blue-5', label: 'H gradient blue 5' },
    { value: 'hq-background-h-gradient-blue-6', label: 'H gradient blue 6' },
    { value: 'hq-background-h-gradient-blue-7', label: 'H gradient blue 7' },
    { value: 'hq-background-h-gradient-yellow-0', label: 'H gradient yellow 0' },
    { value: 'hq-background-h-gradient-yellow-1', label: 'H gradient yellow 1' },
    { value: 'hq-background-h-gradient-yellow-2', label: 'H gradient yellow 2' },
    { value: 'hq-background-h-gradient-yellow-3', label: 'H gradient yellow 3' },
    { value: 'hq-background-h-gradient-green-0', label: 'H gradient green 0' },
    { value: 'hq-background-h-gradient-green-1', label: 'H gradient green 1' },
    { value: 'hq-background-h-gradient-green-2', label: 'H gradient green 2' },
    { value: 'hq-background-h-gradient-green-3', label: 'H gradient green 3' },
    { value: 'hq-background-h-gradient-green-4', label: 'H gradient green 4' },
    { value: 'hq-background-gray-0', label: 'Gray 0' },
    { value: 'hq-background-gray-1', label: 'Gray 1' },
    { value: 'hq-background-h-gradient-gray-0', label: 'H gradient gray 0' },
    { value: 'hq-background-h-gradient-gray-1', label: 'H gradient gray 1' },
    { value: 'hq-background-h-gradient-gray-2', label: 'H gradient gray 2' },
    { value: 'hq-background-h-gradient-gray-3', label: 'H gradient gray 3' },
    { value: 'hq-background-h-gradient-gray-4', label: 'H gradient gray 4' },
    { value: 'hq-background-h-gradient-gray-5', label: 'H gradient gray 5' },
    { value: 'hq-background-h-gradient-gray-6', label: 'H gradient gray 6' },
    { value: 'hq-background-aluminium1', label: 'Aluminium1' },
    { value: 'hq-background-aluminium2', label: 'Aluminium2' },
    { value: 'hq-background-colorful', label: 'Colorful' },
    { value: 'hq-background-carbon-fibre1', label: 'Carbon fibre1' },
    { value: 'hq-background-carbon-fibre', label: 'Carbon fibre' },
    { value: 'hq-background-bricks', label: 'Bricks' },
    { value: 'hq-background-lined-paper', label: 'Lined paper' },
    { value: 'hq-background-blueprint-grid', label: 'Blueprint grid' },
    { value: 'hq-background-blue-flowers', label: 'Blue flowers' },
    { value: 'group-view-css-background', label: 'Group view css background' },
] as const;
